[package]
name = "freqdirs"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "^4.0.0", features = ["derive"] }
fs2 = ">=0.4.3,<0.5.0"
sqlite = ">=0.30.4,<1.0.0"

[build-dependencies]
pathdiff = "^0.2.1"